version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile_flask
        image: esuo/cpsc531project:flask
        volumes:
            - .:/code
    proxy:
        image: nginx
        volumes: # mount custom config at runtime
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "5000:80"
        depends_on:
            - web

