version: '3'
services:
    database:
        image: cassandra:latest
    web:
        build:
            context: .
            dockerfile: Dockerfile_flask
        image: esuo/cpsc531project:flask
        volumes:
            - .:/code
        ports:
            - "5001:5000"
    proxy:
        image: nginx
        volumes: # mount custom config at runtime
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
        ports:
            - "5000:80"

